### ISSUE TITLE
Roadmap to Production

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-dotnet#36]
Here's the roadmap of basic functionalities for `oras-dotnet` to be involved for production use.

- Feature development
  - Models
    - [ ] Model Content Addressable Storage (CAS)
    - [ ] Model Tagging (TagResolver)
    - [ ] Model Target
    - [ ] Model Repository
    - [ ] Model Registry
  - Targets & Functions
    - [ ] Implement Memory Target
    - [ ] Implement File Target
    - [ ] Implement Remote Repository
        - [ ] Support image-spec v1.1.0-rc.5 and distribution-spec v1.1.0-rc.3
    - [ ] Implement Remote Registry
    - [ ] Copy graphs between Targets
    - [ ] Pack Manifests
  - Utilities
    - [ ] Provide Push utility
    - [ ] Provide Fetch utility
    - [ ] Provide Tag utility
    - [ ] Provide Resolve utility
  - Auth
    - [ ] Create an auth client
    - [ ] Support basic auth
    - [ ] Support bearer auth
    - [ ] Support reading credentials from file store
    - [ ] Support reading credentials from docker credential store
  - Performance
    - [ ] Support token cache for auth
    - [ ] Support retry on HTTP requests
- Build & release
  - [ ] Add checks to build and run tests for PRs and commits push to `main` branch
  - [ ] Setup and publish `oras-dotnet` to NuGet
  - [ ] Automate publishing on releasing
  - [ ] Document contributing guide
  - [ ] Document release process
  - [ ] Document release management
- Repository maintenance
  - [ ] Re-arrange repository structure
  - [ ] Add code of conduct
  - [ ] Add security policy
  - [ ] Add dependabot
  - [ ] Add license checker
  - [ ] Add CodeQL checker
  - [ ] Add code coverage check
  - [ ] Add examples to use the library
  - [ ] Add issue template
  - [ ] Add PR template

**Comment by MichaelSimons** [comment]
Is there a timeline for a stable version release?

**Comment by FeynmanZhou** [comment]
> Is there a timeline for a stable version release?



> Is there a timeline for a stable version release?

Hi @MichaelSimons , we don't have a certain time of the stable release yet due to limited resource.

**Comment by karun-verghese** [comment]
@FeynmanZhou is there an update on the timeline?

**Comment by FeynmanZhou** [comment]
> [@FeynmanZhou](https://github.com/FeynmanZhou) is there an update on the timeline?

Hi @karun-verghese , we will release the next mileston v0.3.0 in next few weeks but no certain time commited for the stable release yet. You are welcome to contribute to accelerate the v1.0 process. Thanks

**Comment by Wwwsylvia** [comment]
Hi @karun-verghese, we don't have good samples for the dotnet version at this moment. We have an issue to track this documentation work: #64 
Before the samples are available, you may refer to the `oras-go` [documentation](https://github.com/oras-project/oras-go/blob/main/docs/Modeling-Artifacts.md) and [examples](https://pkg.go.dev/oras.land/oras-go/v2/registry/remote#pkg-examples) which explains some basic concepts that shared between the ORAS SDKs.

**Comment by Wwwsylvia** [comment]
Hi @ridwanabdillahi , [`v0.3.0`](https://github.com/oras-project/oras-dotnet/releases/tag/v0.3.0) is now available! Please check it out and let us know what you think. Your feedback would be greatly appreciated!
